package repository

import (
	"database/sql"
	"errors"

	"github.com/saroel01/aether-cbt/internal/models"
)

// CekLoginRepository manages active exam-session records (the cek_login table) on a
// session_id basis: starting, locking/unlocking, infraction and progress tracking, and
// lookups by session or content token. All session-keyed access is tenant-scoped
// (Requirement 15.2); the content-token lookup is by the unguessable token secret and
// returns the owning tenant for the caller to re-check.
type CekLoginRepository struct {
	db *sql.DB
}

func NewCekLoginRepository(db *sql.DB) *CekLoginRepository {
	return &CekLoginRepository{db: db}
}

const cekLoginColumns = `id, tenant_id, peserta_id, ruang_id, mapel_id, session_id, attempt_token, content_token, locked, tab_switch_count, answered_count, total_questions, login_time, last_activity`

func scanCekLogin(s scanner) (*models.CekLogin, error) {
	c := &models.CekLogin{}
	var ruangID, mapelID, sessionID sql.NullInt64
	var attemptToken, contentToken sql.NullString
	var locked int // stored as INTEGER; converted to bool below
	var lastActivity sql.NullTime
	if err := s.Scan(
		&c.ID, &c.TenantID, &c.PesertaID, &ruangID, &mapelID, &sessionID,
		&attemptToken, &contentToken, &locked, &c.TabSwitchCount, &c.AnsweredCount, &c.TotalQuestions,
		&c.LoginTime, &lastActivity,
	); err != nil {
		return nil, err
	}
	c.RuangID = nullInt(ruangID)
	c.MapelID = nullInt(mapelID)
	c.SessionID = nullInt(sessionID)
	c.AttemptToken = nullString(attemptToken)
	c.ContentToken = nullString(contentToken)
	c.Locked = locked != 0
	c.LastActivity = nullTime(lastActivity)
	return c, nil
}

// Start creates or refreshes a participant's active session for a scheduled exam_session
// and stores the per-attempt token. The unique index (tenant_id, peserta_id, session_id)
// makes a restart an idempotent update rather than a duplicate (Requirement 7.1, 7.2).
// attemptToken is generated by the caller (crypto stays out of the data layer).
func (r *CekLoginRepository) Start(tenantID, pesertaID, sessionID int, attemptToken string) error {
	_, err := r.db.Exec(`
		INSERT INTO cek_login (tenant_id, peserta_id, session_id, attempt_token, login_time, last_activity)
		VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
		ON CONFLICT(tenant_id, peserta_id, session_id) DO UPDATE SET
			attempt_token = excluded.attempt_token,
			login_time = CURRENT_TIMESTAMP,
			last_activity = CURRENT_TIMESTAMP
	`, tenantID, pesertaID, sessionID, attemptToken)
	return err
}

// SetContentToken records the content-serving token issued for the active session
// (Requirement 8.1, AD-2).
func (r *CekLoginRepository) SetContentToken(tenantID, pesertaID, sessionID int, contentToken string) error {
	res, err := r.db.Exec(
		`UPDATE cek_login SET content_token = ?, last_activity = CURRENT_TIMESTAMP WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		contentToken, tenantID, pesertaID, sessionID,
	)
	if err != nil {
		return err
	}
	return requireAffected(res)
}

// Lock marks the active session as server-locked (Requirement 10.2).
func (r *CekLoginRepository) Lock(tenantID, pesertaID, sessionID int) error {
	res, err := r.db.Exec(
		`UPDATE cek_login SET locked = 1 WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		tenantID, pesertaID, sessionID,
	)
	if err != nil {
		return err
	}
	return requireAffected(res)
}

// Unlock clears the server lock (Requirement 10.4).
func (r *CekLoginRepository) Unlock(tenantID, pesertaID, sessionID int) error {
	res, err := r.db.Exec(
		`UPDATE cek_login SET locked = 0 WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		tenantID, pesertaID, sessionID,
	)
	if err != nil {
		return err
	}
	return requireAffected(res)
}

// IsLocked reports whether the active session is currently locked.
func (r *CekLoginRepository) IsLocked(tenantID, pesertaID, sessionID int) (bool, error) {
	var locked int
	err := r.db.QueryRow(
		`SELECT locked FROM cek_login WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		tenantID, pesertaID, sessionID,
	).Scan(&locked)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, ErrNotFound
		}
		return false, err
	}
	return locked != 0, nil
}

// IncrementInfraction advances the infraction counter and returns the new count
// (Requirement 10.1). The threshold→lock decision is a service-level rule.
func (r *CekLoginRepository) IncrementInfraction(tenantID, pesertaID, sessionID int) (int, error) {
	res, err := r.db.Exec(
		`UPDATE cek_login SET tab_switch_count = tab_switch_count + 1, last_activity = CURRENT_TIMESTAMP WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		tenantID, pesertaID, sessionID,
	)
	if err != nil {
		return 0, err
	}
	if err := requireAffected(res); err != nil {
		return 0, err
	}
	var count int
	if err := r.db.QueryRow(
		`SELECT tab_switch_count FROM cek_login WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		tenantID, pesertaID, sessionID,
	).Scan(&count); err != nil {
		return 0, err
	}
	return count, nil
}

// UpdateProgress records the answered/total counts. The client debounces the calls; the
// server performs a single light UPDATE (Requirement 13.2, AD-6).
func (r *CekLoginRepository) UpdateProgress(tenantID, pesertaID, sessionID, answeredCount, totalQuestions int) error {
	res, err := r.db.Exec(
		`UPDATE cek_login SET answered_count = ?, total_questions = ?, last_activity = CURRENT_TIMESTAMP WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		answeredCount, totalQuestions, tenantID, pesertaID, sessionID,
	)
	if err != nil {
		return err
	}
	return requireAffected(res)
}

// GetBySession returns the active session for (tenant, peserta, session), or ErrNotFound.
func (r *CekLoginRepository) GetBySession(tenantID, pesertaID, sessionID int) (*models.CekLogin, error) {
	c, err := scanCekLogin(r.db.QueryRow(
		`SELECT `+cekLoginColumns+` FROM cek_login WHERE tenant_id = ? AND peserta_id = ? AND session_id = ?`,
		tenantID, pesertaID, sessionID,
	))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	return c, nil
}

// GetByContentToken returns the active session that owns the content token, or
// ErrNotFound. The token is the authorization secret for content serving (Requirement
// 8.1); the caller re-checks tenant/window/lock against the returned row.
func (r *CekLoginRepository) GetByContentToken(contentToken string) (*models.CekLogin, error) {
	c, err := scanCekLogin(r.db.QueryRow(
		`SELECT `+cekLoginColumns+` FROM cek_login WHERE content_token = ?`,
		contentToken,
	))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	return c, nil
}

// requireAffected translates a zero-rows-affected UPDATE into ErrNotFound, so tenant- or
// session-keyed updates that match nothing surface as a clear not-found rather than a
// silent no-op.
func requireAffected(res sql.Result) error {
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}
