package handlers

import (
	"testing"

	"github.com/saroel01/aether-cbt/internal/utils"
)

// TestPasswordHashing verifies that the bcrypt password hash helper performs correctly
func TestPasswordHashing(t *testing.T) {
	password := "ruang123"
	
	hash, err := utils.HashPassword(password)
	if err != nil {
		t.Fatalf("Failed to hash password: %v", err)
	}

	if !utils.CheckPasswordHash(password, hash) {
		t.Errorf("Password verification failed for correct password")
	}

	if utils.CheckPasswordHash("wrongpassword", hash) {
		t.Errorf("Password verification succeeded for incorrect password")
	}
}

// TestJWTTokenGeneration verifies token claims creation and validation processes
func TestJWTTokenGeneration(t *testing.T) {
	userID := 42
	tenantID := 1
	role := "supervisor"

	tokenString, err := utils.GenerateToken(userID, tenantID, role)
	if err != nil {
		t.Fatalf("Failed to generate JWT token: %v", err)
	}

	token, err := utils.ValidateToken(tokenString)
	if err != nil {
		t.Fatalf("Failed to validate JWT token: %v", err)
	}

	if !token.Valid {
		t.Errorf("Validated token is reported as invalid")
	}
}

// TestQRCodeGeneration verifies that go-qrcode generates PNG output correctly
func TestQRCodeGeneration(t *testing.T) {
	content := "ujian2026"
	
	pngBytes, err := utils.GenerateQRCode(content, 128)
	if err != nil {
		t.Fatalf("Failed to generate QR Code: %v", err)
	}

	if len(pngBytes) == 0 {
		t.Errorf("Generated QR Code PNG byte slice is empty")
	}

	// Verify PNG signature (first 8 bytes: 137 80 78 71 13 10 26 10)
	if len(pngBytes) > 8 {
		if pngBytes[0] != 137 || pngBytes[1] != 80 || pngBytes[2] != 78 || pngBytes[3] != 71 {
			t.Errorf("Generated byte slice does not feature valid PNG header signature")
		}
	}
}
